version: '3.1'

# https://hub.docker.com/r/holaflenain/stable-diffusion
services:

  easy-diffusion:
    container_name: easy-diffusion
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=01, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9901:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  automatic:
    container_name: automatic
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=02, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9902:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  invoke-ai:
    container_name: invoke-ai
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=03, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9903:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  sd-next:
    container_name: sd-next
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=04, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9904:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  comfy-ui:
    container_name: comfy-ui
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=05, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9905:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  fooocus:
    container_name: fooocus
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=06, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9906:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  stable-swarm:
    container_name: stable-swarm
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=07, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9907:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  volta-ml:
    container_name: volta-ml
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=08, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9908:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  lama-cleaner:
    container_name: lama-cleaner
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=50, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9950:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  facefusion:
    container_name: facefusion
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=51, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York]
    ports: [9951:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}

  kohya:
    container_name: kohya
    image: holaflenain/stable-diffusion:2.0.2
    environment: [WEBUI_VERSION=70, NVIDIA_VISIBLE_DEVICES=all, TZ=America/New_York, LD_LIBRARY_PATH=/usr/lib/wsl/lib/]
    ports: [9970:9000/tcp]
    volumes: 
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui:/opt/stable-diffusion:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/outputs:/outputs:rw
      - \\wsl$\Ubuntu-22.04\home\dom\stable-diffusion-ui/cache:/home/diffusion/.cache:rw
    init: true
    tty: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}
